# Stub profile for dbt parse in CI.
# Uses DuckDB (in-memory, no network) so dbt parse never connects to Snowflake.
# dbt parse validates refs, sources, Jinja, YAML — no SQL execution.
real_estate_analytics:
  target: ci
  outputs:
    ci:
      type: duckdb
      path: ':memory:'
      threads: 1
      schema: DEV
