# Stub profile for dbt compile in CI.
# dbt compile only parses SQL and Jinja — it does NOT connect to the database.
# Snowflake credentials are therefore not required here.
real_estate_analytics:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: "stub-account-for-compile-only"
      user: "ci"
      password: "ci"
      role: DVF_BI_ROLE
      database: DVF_DB
      warehouse: DVF_WH
      schema: DEV
      threads: 1
